[package]
name = "mpvpaper-rs-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Core library for mpvpaper-rs"

[dependencies]
# Wayland
smithay-client-toolkit.workspace = true
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-protocols-wlr.workspace = true
wayland-egl.workspace = true

# Event loop
calloop.workspace = true
calloop-wayland-source.workspace = true

# Graphics
khronos-egl.workspace = true
gl.workspace = true
libloading.workspace = true

# MPV
libmpv2.workspace = true
libmpv2-sys.workspace = true

# CLI
clap.workspace = true
dirs.workspace = true
shlex.workspace = true

# Threading
nix.workspace = true
dashmap.workspace = true

# Logging
colored.workspace = true

# Error handling
anyhow.workspace = true
thiserror.workspace = true
